### ISSUE TITLE
Package installs as "src" from PyPi

### ISSUE THREAD

**Issue by callumforrester** [rajguru7/mkdocs-plugin-inline-svg-mod#1]
When I install this via `pip install` it puts itself in a package called `src` rather than `mkdocs-plugin-inline-svg-mod`, making it essentially anonymous and possibly conflicting with other packages.

I'm not sure how the wheel on PyPi is built but possibly the repo just needs a `pyproject.toml`?

**Comment by rajguru7** [comment]
Thanks. I have updated the build process. Hope this helps!
